import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/Providers";
import { headers } from "next/headers";
import Navbar from "./_components/Navbar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  console.log("root layout.tsx");
  const cookies = (await headers()).get("cookie");

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Navbar />
        <Providers cookies={cookies}>{children}</Providers>
      </body>
    </html>
  );
}
